### ISSUE TITLE
ValueError: kth(=3) out of bounds (1)

### ISSUE THREAD

**Issue by Jokerr-12** [Domattee/gymTouch#1]
I'm sorry to bother you, here is my issue. When I tried to run this env, an error has happened as follow.
**To Reproduce**
```
import gym
import gymTouchTestEnv
import numpy as np
import time
import sys

env = gym.make("TouchTestEgg-v0")
env.reset() 
env.render()    
time.sleep(10)
env.close()
sys.exit()
```
**Error Messages**

> Traceback (most recent call last):
>   File "F:/gymtouch/main.py", line 8, in <module>
>     env.reset() 
>   File "C:\Users\admin\anaconda3\envs\gym\lib\site-packages\gym\envs\robotics\robot_env.py", line 97, in reset
>     obs = self._get_obs()
>   File "f:\gymtouch\gymtouchtestenv\gymTouchTestEnv\envs\touchtest_env.py", line 102, in _get_obs
>     obs["observation_haptic"] = self.touch.get_touch_obs(DiscreteTouch.get_force_relative, 3, scale_linear)
>   File "f:\gymtouch\gymtouch\gymTouch\touch.py", line 361, in get_touch_obs
>     contact_tuples = self.get_contacts(verbose=False)
>   File "f:\gymtouch\gymtouch\gymTouch\touch.py", line 322, in get_contacts
>     nearest_sensor_ids, distances = self.get_k_nearest_sensors(i, rel_geom, CONTACT_NEAREST_K)
>   File "f:\gymtouch\gymtouch\gymTouch\touch.py", line 174, in get_k_nearest_sensors
>     sorted_idxs = np.argpartition(distances, k)
>   File "<__array_function__ internals>", line 6, in argpartition
>   File "C:\Users\admin\anaconda3\envs\gym\lib\site-packages\numpy\core\fromnumeric.py", line 839, in argpartition
>     return _wrapfunc(a, 'argpartition', kth, axis=axis, kind=kind, order=order)
>   File "C:\Users\admin\anaconda3\envs\gym\lib\site-packages\numpy\core\fromnumeric.py", line 57, in _wrapfunc
>     return bound(*args, **kwds)
> ValueError: kth(=3) out of bounds (1)
> 
> Process finished with exit code 1

I tried to changed the "CONTACT_NEAREST_K = 3" to "CONTACT_NEAREST_K = 0" , then it worked, but Is that really the right way?
I'm a student and not good at English, so I'll apologize for any interruption. PLZ give me some help,THANK YOU!

**Comment by Domattee** [comment]
Thank you for the message, the latest commit should fix this issue. This occurres where there is fewer than k sensor points on the sensing geom.
Note that this repository was originally developed for a separate project, [MIMo](https://github.com/trieschlab/MIMo) and is not actively being developed anymore. mimoTouch from MIMo acts as a replacement and has significantly more features, as well as proper documentation.
